JWT_COOKIE_SECURE: no
JWT_TOKEN_LOCATION: ['headers']
JWT_ACCESS_TOKEN_EXPIRES: 86400
JWT_REFRESH_TOKEN_EXPIRES: 432000
SQLALCHEMY_TRACK_MODIFICATIONS: no
DB_URI: 'database.db'
# MAIL_SERVER: 'smtp.yandex.ru'
# MAIL_PORT: 587
# MAIL_USE_TLS: yes
