SPAWN_ADMIN: yes
STRONG_PASSWORD_PATTERN: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[\W_])[A-Za-z\d\W_]{8,}$'
EMAIL_PATTERN: '^\S+@\S+\.\S+$'
# FILE_EXTENSIONS:
#   yaml: ['.yaml', '.yml']
#   json: ['.json']
#   xlsx: ['.xlsx', '.xls']
#   csv: ['.csv']
# COMPANY_REQ_PARAMS: ['name', 'email', 'region', 'number', 'site_url']
